[package]
name = "cuda_manager"
version = "0.1.0"
authors = ["me"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cuda-driver-sys = "0.3"
log = "0.4"
crossbeam = "0.8"

[dev-dependencies]
serial_test = "0.5"
